### ISSUE TITLE
ts428安装失败

### ISSUE THREAD

**Issue by YOHN89** [iranee/qnap-alist-webdav#1]
ts428安装arm_64版本提示失败：
	App Center	App Installation	[App Center] Failed to install 多云盘挂载 3.0.0. The installation package is incompatible. Use the compatible package.

**Comment by iranee** [comment]
你试试其他的安装包，如果不行的话，估计是arm版本没有适配，等我再适配下
ssh运行下命令uname -a 看看你的系统版本
