### ISSUE TITLE
安装后无法打开

### ISSUE THREAD

**Issue by Dev-Wiki** [iranee/qnap-alist-webdav#10]
![image](https://user-images.githubusercontent.com/12946956/201470711-1eb00c1b-5e15-419c-98a0-bca6a4458aed.png)

如上图, 但是 nas 后台是没问题的

![image](https://user-images.githubusercontent.com/12946956/201470721-5a6c6c4d-a275-4faa-867e-0580ed0af41c.png)

**Comment by zeisscai** [comment]
图一那个从图标点开跳转的地址你可以在安装后过一段时间尝试打开。
还可以试试 http://ip:5244/@login 这个网址。
我的设备是ts-428，QTS 5.0.1.2194

**Comment by iranee** [comment]
> ![image](https://user-images.githubusercontent.com/12946956/201470711-1eb00c1b-5e15-419c-98a0-bca6a4458aed.png)
> 
> 如上图, 但是 nas 后台是没问题的
> 
> ![image](https://user-images.githubusercontent.com/12946956/201470721-5a6c6c4d-a275-4faa-867e-0580ed0af41c.png)

也可能是版本内核不对，换个其他版本文件试试，例如x86_x64
