### ISSUE TITLE
威联通TS-212P，无法安装

### ISSUE THREAD

**Issue by KimiMeta** [iranee/qnap-alist-webdav#12]
大佬您好！威联通TS-212P，下载的alist_3.5.1_arm_64.qpkg，无法安装。
[App Center] Failed to install 多云盘挂载 3.5.1. Installation package is incompatible. Use the correct package.	

辛苦大佬能早日解决，感谢感谢！

**Comment by iranee** [comment]
TS-212P应该安装arm-x19这个版本吧，之前安装是哪个版本？或者qq我debug

**Comment by KimiMeta** [comment]
大佬，我刚刚安装arm-x19成功了，但是从NAS上打开alist，无法访问192.168.50.129:5244，进步了后台，请问这个是什么原因？

**Comment by iranee** [comment]
进不了后台表示版本不对，应该是你的NAS版本低，可以按照下面提示试下
`ARM版因为权限问题，安装过后要手动给安装目录0777权限，可以用winscp设置，也可以用PuTTy来执行代码：
chmod -Rf 777 $(/sbin/getcfg alist Install_Path -f /etc/config/qpkg.conf)/*.*
`

**Comment by babylife** [comment]
TS-420安装最新的版本一样的问题，但是安装3.4.0没有问题，使用的是X19的版本。 请问作者是否可以帮忙修复下这个问题。
权限已经修改，感谢

![image](https://user-images.githubusercontent.com/31977161/219942051-ef110b17-4e60-4bc6-938b-b32660c46821.png)
![image](https://user-images.githubusercontent.com/31977161/219942061-6e29144b-f83c-4a0e-86dc-b81a1d57d51a.png)
