### ISSUE TITLE
威联通HBS3挂载WEBDAV时报系统错误

### ISSUE THREAD

**Issue by MR-liu** [iranee/qnap-alist-webdav#13]
威联通HB3挂载WEBDAV时报系统错误，不知道该怎么用HBS3挂载alist

**Comment by iranee** [comment]
* 注意：威联通HBS3挂载的名称必须为英文，不能挂载/dav/根目录，要带网盘的挂载路径
* 例如阿里云盘的alist挂载目录名称是aliyundrive
* 挂载URL：http://127.0.0.1:5244/dav/aliyundrive

**Comment by GohUnTsuan** [comment]
> * 注意：威联通HBS3挂载的名称必须为英文，不能挂载/dav/根目录，要带网盘的挂载路径
> * 例如阿里云盘的alist挂载目录名称是aliyundrive
> * 挂载URL：http://127.0.0.1:5244/dav/aliyundrive

同样提示挂载错误，在浏览器中直接键入`http://127.0.0.1:5244/dav/aliyundrive`，并输入用户名密码后，跳转到空白页面提示`Not Found`，何解？
