### ISSUE TITLE
有没有可能自动识别系统构架，从alist官方自动下载最新的符合对应系统的二进制包？

### ISSUE THREAD

**Issue by tychenjiajun** [iranee/qnap-alist-webdav#17]
如题。我感觉 pkg_install 里执行相关的命令的话这个是可以实现的吧？

**Comment by zycboss** [comment]
主要是github在国内很多网络无法访问，要在线更新还得挂梯子，不能指望所有人NAS都一直挂着梯子吧

**Comment by tychenjiajun** [comment]
> 威联通的安装包没有通用版，例如arm的只能下载arm对应的版本，版本错误就不让安装。 可以制作成获取最新版本alist，但是受限于网络，如果下载不成功，或者因为网络延迟高会导致安装失败。


嗯，我发现确实是只能下载对应版本。不过也许可以制作一个类似 https://www.qnapclub.eu/en/repo.xml 的文件，部署在github pages或者其他静态服务器上。模仿 https://github.com/tailscale/tailscale-qpkg/tree/main/build ，利用GitHub actions自动打包、发布和部署repo.xml文件
