### ISSUE TITLE
3.3 後 x86 版本開始有問題

### ISSUE THREAD

**Issue by Enterpr1se** [iranee/qnap-alist-webdav#18]
3.3 x86 版本正常
但不知為甚麽 3.4 如果使用 HTTPS 就會出問題，但 HTTP 則正常
而 3.5 開始，即使沒有使用 HTTPS 依然不能啓動

使用 QNAP TS-439 OS 4.2.6 版本

**Comment by iranee** [comment]
从3.5开始，alist升级了依赖包libc.so.6，导致通用版不可用，你尝试安装x86_x64版本试试，如果安装不成功，我单独打包一下发给你。或者进入ssh，手动下载二进制文件，看看哪个可以运行，我集成到插件里。
二进制包：https://github.com/alist-org/alist/releases/tag/v3.10.1
有问题请联系我qq 195408188

**Comment by tychenjiajun** [comment]
https://github.com/tychenjiajun/qnap-alist-webdav/suites/10829104245/artifacts/545249436

看看这里的行不行
