### ISSUE TITLE
阿里云挂载无法预览和下载，请求修复

### ISSUE THREAD

**Issue by onelxzy** [iranee/qnap-alist-webdav#20]
阿里云挂载无法预览和下载，请求修复

**Comment by tychenjiajun** [comment]
https://github.com/alist-org/alist/issues/3375

**Comment by 1411v6** [comment]
https://github.com/alist-org/alist/releases/tag/v3.11.0  官方已更新，请求更新

**Comment by tychenjiajun** [comment]
> https://github.com/alist-org/alist/releases/tag/v3.11.0 官方已更新，请求更新

临时方案：fork我的fork，修改cfg文件里的版本号，会自动打包到github actions里。

点开actions详情，在artifacts里就可以下载
![Screenshot_2023-02-15-08-57-31-984_org mozilla fennec_fdroid-edit](https://user-images.githubusercontent.com/6280428/218897706-6840d737-48b6-4872-9267-903553f51e3c.jpg)

reference #19

**Comment by 1411v6** [comment]
> > https://github.com/alist-org/alist/releases/tag/v3.11.0官方已更新，请要求更新
> 
> 临时方式：fork我的fork，修改cfg文件里的版本号，会自动打包到github actions里。
> 
> 点开actions详情，在artifacts里就可以下载 ![Screenshot_2023-02-15-08-57-31-984_org mozilla fennec_fdroid-edit](https://user-images.githubusercontent.com/6280428/218897706-6840d737-48b6-4872-9267-903553f51e3c.jpg)
> 
> 参考#19

好的  已经fork  已成功构建

**Comment by paidax79** [comment]
遇到一个问题：安装3.11威联通版二进制版之后，原本以webdev云服务的形式挂载的阿里云速度测试可以通过且正常，但是无法在文件系统中进入，而更改为以webdev远程设备的形式挂载之后就能够进入，并能够复制东西……
感觉像是威联通这边的问题，不确定是HybridMount的问题还是文件管理的问题。
但是之前3.9版本的时候能够正常使用。
设备:TS-551 (j3355 2core 2thread 2500MHz)
内存：6G
版本：5.0.1.2277

**Comment by 1411v6** [comment]
> ：安装3.11威联威联之后之后之后挂载进入，并进入进入东西东西东西东西东西东西东西是的的问题问题问题问题问题问题问题问题问题问题问题这边这边这边这边这边这边这边这边这边这边这边这边这边这边这边这边这边这边这边这边这边这边这边确定确定确定是是是是是 是 是 是(j3355 2core 2thread 2500MHz) 内存：6G QTS版本：5.0.1.2277 Alist版本：3.11
> 
> ps:只阿里云盘会出现这个问题，百度云盘可以正常挂载

威联通把HybridMount更新了，所以会出现这个问题

**Comment by tychenjiajun** [comment]
> 遇到一个问题：安装3.11威联通版二进制版之后，原本以webdev云服务的形式挂载的阿里云速度测试可以通过且正常，但是无法在文件系统中进入，而更改为以webdev远程设备的形式挂载之后就能够进入，并能够复制东西…… 感觉像是威联通这边的问题，不确定是HybridMount的问题还是文件管理的问题。 但是之前3.9版本的时候能够正常使用。 设备:TS-551 (j3355 2core 2thread 2500MHz) 内存：6G QTS版本：5.0.1.2277 Alist版本：3.11
> 
> ps:仅阿里云盘会出现这个问题，百度云盘可以正常挂载

建议另外开issue
