### ISSUE TITLE
TS420无法打开首页版本

### ISSUE THREAD

**Issue by babylife** [iranee/qnap-alist-webdav#23]
TS-420安装最新的版本，无法打开5244的管理主页。 
补充硬件信息
https://www.qnap.com.cn/zh-cn/product/ts-420/specs/hardware 

**处理器 | Marvell 1.6GHz**
测试最新的几个版本都有问题，看到先前closed的issue，作者建议使用3.4.0测试。发现安装3.4.0没有问题，使用的都是X19的版本。 
请问作者是否可以帮忙修复下这个问题。或者给一些排查建议？
另权限使用winscp已经修改，截图如下。3.4版本不需要做任何权限设置都可以进入5244的管理首页

![image](https://user-images.githubusercontent.com/31977161/219942180-d2108bfd-4bbe-4c5e-82c3-2fdf4d5e6416.png)
==
权限修改如下：
![image](https://user-images.githubusercontent.com/31977161/219942190-ac8277ac-2d80-413f-9301-ac5254d516b5.png)
![image](https://user-images.githubusercontent.com/31977161/219942194-4cda90b7-3524-4008-91d8-b6479fa781bc.png)

**Comment by iranee** [comment]
你试下alist_3.11.0_arm-x19-alist-linux-musl-arm.qpkg版本
这个用的arm通用版
如果还不行，你得去https://github.com/alist-org/alist/releases/tag/v3.11.0 打包好的二进制替换，将不同的arm版本替换进去测试。如果有能运行的，告诉我，我更新下

**Comment by iranee** [comment]
替换过的二进制，设置好权限，在putty里运行/share/CACHEDEV1_DATA/.qpkg/alist/alist
如果有显示：
A file list program that supports multiple storage,
built with love by Xhofe and friends in Go/Solid.js.
Complete documentation is available at https://alist.nn.ci/

Usage:
  alist [command]

表示这个版本就是对的。

**Comment by babylife** [comment]
> 

感谢回复且提供排查思路：

alist_3.11.0_arm-x19-alist-linux-musl-arm.qpkg 一样的错误。
无法访问此网站qnap 拒绝了我们的连接请求.

后来我用原来的版本alist_3.11.0_arm-x19.qpkg 做了测试的到了报错信息：我猜测是依赖库的问题。 

/share/HDA_DATA/.qpkg/alist/alist: /lib/libc.so.6: version `GLIBC_2.28' not found (required by /share/HDA_DATA/.qpkg/alist/alist)

而使用您建议的alist_3.11.0_arm-x19-alist-linux-musl-arm.qpkg版本，得到了下面的错误
[/] # /share/HDA_DATA/.qpkg/alist/alist
Illegal instruction

我试过官方的BIN文件，得到的错误会有下面几种，根据我的理解，GLIBC_2.28可能是RCA。不知道有什么办法解决？

![image](https://user-images.githubusercontent.com/31977161/220222493-125bf28c-6b63-4bab-864b-55425d6a5eec.png)

**Comment by babylife** [comment]
大佬抱歉我不懂编译这个东西，现在还有什么办法解决吗？

**Comment by babylife** [comment]
[~] # uname -a
Linux QNAP 3.4.6 #1 Thu Nov 24 07:05:06 CST 2022 armv5tel unknown

不知道大神是否可以帮忙编译支持这个架构的版本？

**Comment by iranee** [comment]
我不懂静态依赖库编译，昨天查了些资料，QNAP的系统不可以手动更新依赖库的版本。

**Comment by babylife** [comment]
那是不是无解了？只能用老版本了？
