### ISSUE TITLE
新建文件夹是以admin创建的

### ISSUE THREAD

**Issue by flashlab** [iranee/qnap-alist-webdav#24]
在网页端新建文件夹默认是admin角色创建的，而NAS一般都会禁用admin账户，导致其他程序（比如威联通的file station）没有访问权限，有没有办法以非admin角色创建呢？感觉docker版的话应该没这个问题

**Comment by iranee** [comment]
这个用户角色是系统定的，个人改不了

**Comment by flashlab** [comment]
刚发现alist官方仓库似乎增加了这个功能 https://github.com/alist-org/alist/commit/923937b530625d9b4fab6bf137aae053004cd760 ，3.12.0版本生效？待确认

**Comment by iranee** [comment]
我还未尝试，你的意思是在命令前加入指定umask来运行吗？
umask 0 && alist server 
是这样吗？

**Comment by flashlab** [comment]
不是的，这个应该是alist的bug，local存储可以设置新建文件的权限，但是对文件夹无效，新版似乎修复了这个问题

**Comment by iranee** [comment]
我测试过了，只要是插件下运行的二进制文件创建的文件夹，权限都是当前用户，其他用户都不可用。除非给权限0755~0777，或者就是在插件的启动文件里添加自动给权限命令，这个功能也不容易实现。
