### ISSUE TITLE
只有第一次可以在 HybridMount 挂载成功

### ISSUE THREAD

**Issue by KarLYelin** [iranee/qnap-alist-webdav#28]
QTS 5.1 Beta
在最新版本的 HybridMount 只能在第一次挂载成功，再次连接就不能挂载了

**Comment by iranee** [comment]
测试下新版本，如果还是不可用，等官方修复。

**Comment by KarLYelin** [comment]
> 测试下新版本，如果还是不可用，等官方修复。

不可用，只能使用 HBS3 慢慢同步。

**Comment by KarLYelin** [comment]
解决方案是，把 NAS 的 WebDAV 挂到 Alist 上，然后在 alist 创建一个复制任务

**Comment by iranee** [comment]
我这里测试正常，跑满宽带，看看是不是HBS3版本低的问题
