### ISSUE TITLE
請問有機會增加 x86 版本嗎？

### ISSUE THREAD

**Issue by Enterpr1se** [iranee/qnap-alist-webdav#3]
我仍使用老而彌堅的 TS-439，十年了，還正常運作
請問可以制作 X86 版本嗎？
謝謝

**Comment by iranee** [comment]
可以的，晚上见。

**Comment by Enterpr1se** [comment]
不行，安裝失敗

**Comment by iranee** [comment]
已编译386(x86)版本，测试下。
如果还不行，请贴出NAS的系统版本和处理器型号

**Comment by Enterpr1se** [comment]
成功了，謝謝

另外想請問一下，Alist 是否不需要密碼就可以訪問呢?
我已經將 Guest 帳號「無密碼訪問」權限取消，但沒有效果

現在只好開一個空白資料夾給 Guest 帳號來訪問

**Comment by iranee** [comment]
这需要阅读官方的文档，看看有没有相关设置，或者等待更新。
