### ISSUE TITLE
一个冲突（？）

### ISSUE THREAD

**Issue by elviscai** [iranee/qnap-alist-webdav#32]
环境：TS-262C QTS5.1.0.2444
前提：安装和使用 [Gitea](https://www.myqnap.org/repo/Gitea_1.20.1.0_x86_64.qpkg)
问题：装了咱们这个 Alsit 后，无论是否启动，Gitea 进仓库都会提示 `Error 500 open /dev/null: permission denied`；卸载 Alist 后，Gitea 恢复正常。

**Comment by iranee** [comment]
插件间没有相关联的，你在安装过alist的插件后，重新安装下Gitea试试
