### ISSUE TITLE
升级3.26后原来的账号密码无法登录，提示密码错误

### ISSUE THREAD

**Issue by ausmas** [iranee/qnap-alist-webdav#34]
升级3.26后原来的账号密码无法登录，提示密码错误

**Comment by iranee** [comment]
原密码是否有特殊字符，要么全新安装试下
或者降级改密码后再升级

**Comment by ausmas** [comment]
有特殊字符，目前降级试了也不行，不知道下个版本能不能解决，不行就只能重装了

**Comment by ausmas** [comment]
ssh进入alist qpkg安装目录，然后
# 随机生成一个密码
./alist admin random
# 手动设置一个密码,`NEW_PASSWORD`是指你需要设置的密码
./alist admin set NEW_PASSWORD
