### ISSUE TITLE
使用默认用户名密码无法登录

### ISSUE THREAD

**Issue by ZhangYong-Pioneer** [iranee/qnap-alist-webdav#4]
如图，用户名=admin，密码=123456
无法登录，还是提示输入用户名密码
（不知道还需要其他什么特别配置吗。。。）

<img width="321" alt="image" src="https://user-images.githubusercontent.com/100743729/197919426-c784fe32-92ab-4f9b-928c-83ec3d6f550d.png">

**Comment by iranee** [comment]
什么机型？如果可以的话，建议进入SSH，进入安装目录，运行./alist admin 看看用户名密码是否未初始化。
或者安装下低版本的试试，QQ 195408188可以询问

**Comment by routescroll** [comment]
不好意思隔了快一年才回复。当时提了这个issue后就忘了，也没继续使用这个应用。

最近想在qnap下挂载阿里云盘，发现还是有这个问题。
NAS是QNAP的TS-431K，
安装的是arm-x41的3.24版本
ssh进入alist的安装目录，运行./alist admin，返回的结果如下：
```
INFO[2023-09-29 00:28:41] reading config file: data/config.json        
INFO[2023-09-29 00:28:41] load config from env with prefix: ALIST_     
INFO[2023-09-29 00:28:41] init logrus...                               
INFO[2023-09-29 00:28:41] admin user's info: 
username: admin
password: 123456 
```
网页端用这个用户名和密码还是无法登录，和去年一模一样的现象。
不知道还有什么方法能确认原因么。
谢谢！
