### ISSUE TITLE
迅雷云盘总是添加失败，偶尔成功也是很快过期。

### ISSUE THREAD

**Issue by curryhendry** [iranee/qnap-alist-webdav#42]
Failed init storage: ErrorCode: 4002 ,Error: captcha_invalid ,ErrorDescription: client_id:"Xp6vsxz_7IYVw2BB" meta:{key:"phone_number" value:"+86 18*********"} meta:{key:"result" value:"review"} result:review

感谢指点

**Comment by curryhendry** [comment]
> 我也遇到了这个问题，请问解决了吗

没，没人理

**Comment by iranee** [comment]
这个问题应该去官方提交问题 Alist 版开源：https://github.com/alist-org/alist

这里只是将官方的文件做了打包做成插件。
