### ISSUE TITLE
115存储打不开了

### ISSUE THREAD

**Issue by SingleRottenChips** [iranee/qnap-alist-webdav#50]
> failed get objs: failed to list objs: invalid character 'a' looking for beginning of value

官方那边我也提交了[issue](https://github.com/alist-org/alist/issues/7191).

**Comment by Logzhan** [comment]
兄弟你提交issue的速度太快了，貌似今晚115出问题后，我也发现了这个问题，我用py115这个项目之前是能获列表的，现在不行了。然后我抓了下115的接口，调整了部分内容，py115可以获取到文件列表了，估计alist也是这个情况。

**Comment by NICPA314** [comment]
蹲

**Comment by SingleRottenChips** [comment]
> 兄弟你提交issue的速度太快了，貌似今晚115出问题后，我也发现了这个问题，我用py115这个项目之前是能获列表的，现在不行了。然后我抓了下115的接口，调整了部分内容，py115可以获取到文件列表了，估计alist也是这个情况。

我只是正好要离线下载才偶然发现的，然后就秉持“发现问题尽早上报”的原则…… (另外发现这问题之前还遇到了115网页端打开文件夹加载卡顿的问题，这个之前也遇到过几次。）

**Comment by Logzhan** [comment]
我刚刚https://github.com/SheltonZhu/115driver/tree/main这个仓库下载下来编译了，奇怪的是，这个能获得列表信息的。一下子不知道原因是什么了。官方应该解决比较快。

**Comment by Logzhan** [comment]
我解决了。https://github.com/alist-org/alist/issues/7191

**Comment by ailg666** [comment]
看来都是一样的问题，115官发被攻击之后恢复服务就变成这样子了……或许调整了某些服务端的东西

**Comment by iranee** [comment]
官方已修复！
