### ISSUE TITLE
挂载到HYBRIDMOUNT 的问题

### ISSUE THREAD

**Issue by MasterBMW** [iranee/qnap-alist-webdav#55]
最新版3.40版本，挂载115网盘都正常，alist里面下载，播放都是没问题的， 但是用HYBRIDMOUNT 挂载云盘以后，挂载是可以成功挂载，但是没办法更新文件列表，一直转圈圈，大佬有没有解决办法？

**Comment by iranee** [comment]
> 最新版3.40版本，挂载115网盘都正常，alist里面下载，播放都是没问题的， 但是用HYBRIDMOUNT 挂载云盘以后，挂载是可以成功挂载，但是没办法更新文件列表，一直转圈圈，大佬有没有解决办法？

试试3.41版

**Comment by MasterBMW** [comment]
下载还是3.40版本，是不是还没更新上？
