### ISSUE TITLE
使用HBS工具时提示 收到云服务错误

### ISSUE THREAD

**Issue by TomatoFryEggs** [iranee/qnap-alist-webdav#7]
用iOS的Documents可以添加此WebdDAV服务，但是添加到HBS就是不行

**Comment by TomatoFryEggs** [comment]
我在哪可以看到日志？

**Comment by TomatoFryEggs** [comment]
换了个根目录为备份目录的账号好了，没排查是admin原因还是根目录原因。

**Comment by iranee** [comment]
> 换了个根目录为备份目录的账号好了，没排查是admin原因还是根目录原因。
HBS添加挂载过的目录，必须要英文名字
例如挂载阿里云盘名字是aliyundrive，Webdav的目标地址是http://127.0.0.1:5244/dav/aliyundrive
