### ISSUE TITLE
HBS3 无法通过webdav挂载【改英文名称后挂载成功】

### ISSUE THREAD

**Issue by allok1985** [iranee/qnap-alist-webdav#9]
主要是想挂载夸克盘备份数据
HBS3 无法通过webdav挂载  提示收到云服务器错误
能够通过hyb网络磁盘装载  不能共享和通过hbs3访问

**Comment by iranee** [comment]
HBS3挂载的时候，需要输入完整的webdav路径
例如阿里云盘挂载的名字是aliyundriver ,注意挂载的名字必须为英文：
https://127.0.0.1:5244/dav/aliyundriver

**Comment by allok1985** [comment]
还是要吐槽一下  alist的教程图片都是挂载的中文目录

**Comment by iranee** [comment]
> 还是要吐槽一下 alist的教程图片都是挂载的中文目录

这个跟系统软件有关系，威联通的HBS3不一定通用。
